refactor: update CI workflow to replace 'Ubuntu' with 'Linux' in job names and conditions

diff --git a/.github/workflows/Test.yml b/.github/workflows/Test.yml
--- a/.github/workflows/Test.yml
+++ b/.github/workflows/Test.yml
@@ -36,13 +36,33 @@ jobs:
 # ------------------------------------------------------------------------------------------------------
 # Restore static site content
 # ------------------------------------------------------------------------------------------------------         
-        -   name: Restore static site content
+        -   name: Restore static site content -Windows
+            if: runner.os == 'Windows'
             uses: actions/cache@v3.2.6
             with:
                 path: ./**
                 key: cache-site-windows-${{ github.run_number }}
                 enableCrossOsArchive:
                     true
+
+        -   name: Restore static site content - Linux
+            if: runner.os == 'Linux'
+            uses: actions/cache@v3.2.6
+            with:
+                path: ./**
+                key: cache-site-linux-${{ github.run_number }}
+                enableCrossOsArchive:
+                    true
+
+        -   name: Restore static site content - macOS
+            if: runner.os == 'macOS'
+            uses: actions/cache@v3.2.6
+            with:
+                path: ./**
+                key: cache-site-windows-${{ github.run_number }}
+                enableCrossOsArchive:
+                    true
+                
 
 # ------------------------------------------------------------------------------------------------------
 # Install .Net core SDK 8.0.100
@@ -106,14 +126,14 @@ jobs:
 # Run .Net Framework tests using powershell and publish the results
 # ------------------------------------------------------------------------------------------------------
         -   name: Run tests for Ginger .NetFramework *Test Dlls for Windows
-            if: success() || failure() && startsWith(runner.os, 'Windows')        # run this step even if previous step failed and if the OS is Windows
+            if: success() || failure() && (runner.os == 'Windows')        # run this step even if previous step failed and if the OS is Windows
             run: powershell -file "TestDotNetFrameworkGithub.ps1"
   
 # ------------------------------------------------------------------------------------------------------
 # Run Standalone CLI Test
 # ------------------------------------------------------------------------------------------------------          
-        -   name: Run Standalone CLI Test for Ubuntu
-            if: success() || failure() && startsWith(runner.os, 'Linux')       # run this step even if previous step failed
+        -   name: Run Standalone CLI Test for Linux
+            if: success() || failure() && (runner.os == 'Linux')       # run this step even if previous step failed
             shell: bash
             run: |
                 pwd 
@@ -128,15 +148,15 @@ jobs:
 # ------------------------------------------------------------------------------------------------------
         -   name: Test Report - Windows
             uses: dorny/test-reporter@v1
-            if: success() || failure() && startsWith(runner.os, 'Windows')        # run this step even if previous step failed
+            if: success() || failure() && (runner.os == 'Windows')        # run this step even if previous step failed
             with:
                 name: Ginger Windows UnitTests    # Name of the check run which will be created
                 path: "D:/a/TestResults/*.trx"                # Path to test results
                 reporter: dotnet-trx            # Format of test results
                 
-        -   name: Test Report - Ubuntu
+        -   name: Test Report - Linux
             uses: dorny/test-reporter@v1
-            if: success() || failure()   && startsWith(runner.os, 'ubuntu')      # run this step even if previous step failed
+            if: success() || failure()   && (runner.os == 'Linux')      # run this step even if previous step failed
             with:
                 name: Ginger Linux UnitTests    # Name of the check run which will be created
                 path: "**/*.trx"                # Path to test results
@@ -144,7 +164,7 @@ jobs:
 
         -   name: Test Report - MacOS
             uses: dorny/test-reporter@v1
-            if: success() || failure()  && startsWith(runner.os, 'macos')       # run this step even if previous step failed
+            if: success() || failure()  && (runner.os == 'macOS')       # run this step even if previous step failed
             with:
                 name: Ginger MacOS UnitTests    # Name of the check run which will be created
                 path: "**/*.trx"                # Path to test results
